kind: Pod
apiVersion: v1

metadata:
  name: my-pod
  labels:
    app: my-pod

spec:
  containers:
  - name: mypod-container
    image: busybox:1.28
    command: ['sh','-c','echo the app is running && sleep 3600']
    env:
    - name: firstname
      value: "vivek" 
  initContainers:
  - name: init-myservice
    image: busybox:1.28
    command: ['sh','-c']
    args: ['unitl nslookup myservice.default.svc.cluster.local; do echo waiting for service to be up; sleep 2; done']
